## Numpy

Grundwerkzeug für Zahlenverarbeitung in Python

Geschrieben in C -> Performant

In [1]:
import numpy as np

### Array

N-Dimensionales Array mit beliebigen Werten

Datentypen können nicht gemischt werden

In [5]:
a = np.array([1, 2, 3, 4])

In [6]:
a

array([1, 2, 3, 4])

In [8]:
a.dtype  # 8 Byte pro Zahl -> ineffizient

dtype('int64')

#### Datentypen

In Numpy gibt es mehrere Datentypen zur Auswahl

Ganze Zahlen:
- Int64
- Int32
- Int16
- Int8

Kommazahlen:
- Float64
- Float32
- Float16

In [9]:
b = np.array([1, 2, 3, 4], dtype=np.int8)

In [10]:
b

array([1, 2, 3, 4], dtype=int8)

In [15]:
b.size  # Gesamtanzahl Elemente (funktioniert auch bei mehreren Dimensionen)

4

In [16]:
len(b)

4

In [18]:
b.ndim  # Anzahl Dimensionen

1

In [20]:
b.shape  # Größe der Seitenlängen (hier 4)

(4,)

#### Index

Funktioniert wie in Python

In [67]:
b[0]

np.int8(1)

In [68]:
b[-1]

np.int8(4)

In [69]:
b[1:3]

array([2, 3], dtype=int8)

### Matrizen

Über np.array kann auch ein mehrdimensionales Array erstellt werden

In [22]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [23]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
c.size

9

In [25]:
len(c)

3

In [26]:
c.ndim

2

In [27]:
c.shape

(3, 3)

#### Index bei Matrix

In [70]:
c[0]

array([1, 2, 3])

In [71]:
c[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [72]:
c[-1]

array([7, 8, 9])

In [74]:
c[1][1]  # Die mittlere Stelle

np.int64(5)

In [76]:
c[1, 1]  # In Numpy möglich, in Python nicht möglich

np.int64(5)

In [77]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
c[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [88]:
c[:, 1]  # Doppelpunkt: Alles

array([2, 5, 8])

#### Einfache Funktionen

In [31]:
c.sum()  # Gesamtsumme aller Elemente

np.int64(45)

In [32]:
c.mean()

np.float64(5.0)

In [37]:
c.std()

np.float64(2.581988897471611)

In [38]:
c.var()

np.float64(6.666666666666667)

In [42]:
c.sum(axis=0)  # Y-Achse

array([12, 15, 18])

In [43]:
c.sum(axis=1)  # X-Achse

array([ 6, 15, 24])

In [47]:
np.arange(10)  # Numpy Array aus einer Range erstellen

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Vektorisierung

Gesamtes Array mit einer Operation verarbeiten

U.a. für Boolean Masken essentiell

In [48]:
d = np.arange(10)

In [50]:
d * 2  # Jede Zahl mit 2 multipliziert

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
for x in d:
    print(x * 2)

0
2
4
6
8
10
12
14
16
18


In [52]:
d % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [53]:
d ** 5

array([    0,     1,    32,   243,  1024,  3125,  7776, 16807, 32768,
       59049])

In [54]:
e = np.arange(10)

In [56]:
d * e  # Zwei Arrays miteinander vektorisieren

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [58]:
c * c  # Auch bei Matrizen möglich

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

### Boolean Masken

Vektorisierung mit einer booleschen Operation

Bringt als Ergebnis ein Numpy Array mit True/False gefüllt

Verwendung: Filterung

In [59]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
d > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [62]:
d[d > 5]  # Hier werden alle Werte ausgegeben, welche bei der Boolean Maske True stehen haben

array([6, 7, 8, 9])

In [63]:
d % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [64]:
d[d % 2 == 0]

array([0, 2, 4, 6, 8])

In [65]:
mod2 = d % 2 == 0

In [66]:
d[mod2]

array([0, 2, 4, 6, 8])

### Performance

In [98]:
import time
def measureTime(func, *args, **kwargs):
    start = time.time()
    func(*args, **kwargs)
    end = time.time()
    print(end - start)

In [105]:
def pythonList(anz):
    return list(range(anz))

In [106]:
def numpyArray(anz):
    return np.arange(anz)

In [108]:
x = measureTime(pythonList, 500_000_000)

8.35431456565857


In [109]:
y = measureTime(numpyArray, 500_000_000)

0.7929317951202393


In [110]:
import sys

In [111]:
z = 10

In [113]:
sys.getsizeof(z)  # Python Int benötigt 28B

28

### Weitere Funktionen

#### Zufallszahlen

In [115]:
np.random.random()  # Zufallszahl von 0-1

0.13678136207039415

In [121]:
np.random.random(size=(3, 3))  # Zufallszahlen Array in der Form 3x3

array([[0.53181716, 0.80670188, 0.04712398],
       [0.85547554, 0.17789844, 0.65867378],
       [0.85667727, 0.59970919, 0.87866179]])

In [122]:
np.random.random(size=10)

array([0.77545805, 0.37453274, 0.30261535, 0.46476244, 0.8205531 ,
       0.53033615, 0.91544102, 0.02954573, 0.16602974, 0.60424279])

In [127]:
np.random.randint(10)  # Zufallszahl von 0-9

9

In [131]:
for x in range(10):
    print(np.random.randint(10))

5
3
7
0
3
1
0
8
4
0


In [133]:
np.random.randint(10, size=(10, 10), dtype=np.int8)

array([[3, 2, 7, 7, 2, 2, 5, 7, 0, 3],
       [2, 0, 0, 3, 7, 1, 9, 0, 2, 9],
       [2, 0, 3, 0, 2, 6, 1, 7, 9, 6],
       [7, 4, 4, 4, 3, 7, 7, 4, 2, 1],
       [1, 7, 2, 9, 7, 4, 4, 8, 8, 9],
       [3, 5, 4, 5, 7, 6, 0, 8, 4, 2],
       [4, 5, 5, 6, 2, 0, 9, 6, 9, 4],
       [6, 8, 3, 0, 6, 1, 4, 1, 8, 4],
       [0, 0, 5, 2, 7, 8, 8, 6, 5, 7],
       [9, 7, 3, 8, 5, 6, 4, 1, 6, 8]], dtype=int8)

#### Reshape

Form von einem Array ändern

- 1D <-> 2D
- 10x10 -> 20x5 -> 100x1

In [136]:
np.arange(10).reshape(5, 2)  # 5 Zeilen, 2 Spalten

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [137]:
np.arange(10).reshape(2, 5)  # 2 Zeilen, 5 Spalten

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [146]:
np.arange(10).reshape(10, -1)  # -1: Platzhalter für die Länge des Arrays

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [147]:
np.random.randint(10, size=(10, 10))

array([[1, 1, 5, 1, 8, 9, 6, 0, 7, 3],
       [1, 0, 0, 8, 3, 4, 8, 4, 8, 1],
       [6, 8, 1, 2, 4, 9, 9, 2, 5, 5],
       [2, 7, 4, 6, 3, 2, 2, 5, 0, 2],
       [5, 7, 8, 1, 7, 9, 4, 4, 0, 2],
       [9, 5, 8, 6, 8, 0, 4, 1, 4, 5],
       [5, 3, 4, 0, 0, 1, 1, 5, 4, 0],
       [8, 8, 8, 5, 7, 1, 8, 0, 0, 1],
       [3, 3, 6, 2, 8, 2, 2, 4, 0, 4],
       [9, 8, 4, 8, 7, 4, 6, 7, 0, 1]], dtype=int32)

In [154]:
np.random.randint(10, size=(10, 10)).reshape(-1,)  # -1,: Array glätten

array([0, 8, 9, 2, 2, 8, 6, 7, 0, 9, 4, 5, 3, 9, 2, 0, 5, 5, 6, 3, 2, 4,
       4, 9, 1, 3, 4, 2, 0, 5, 3, 3, 6, 7, 9, 9, 7, 6, 4, 3, 7, 2, 9, 4,
       3, 2, 3, 3, 0, 4, 3, 6, 1, 0, 8, 9, 4, 2, 1, 2, 4, 7, 4, 9, 4, 3,
       6, 4, 8, 3, 4, 6, 9, 6, 8, 9, 3, 3, 6, 8, 9, 9, 6, 5, 3, 8, 5, 9,
       7, 4, 6, 6, 8, 5, 7, 0, 0, 1, 9, 0], dtype=int32)

In [157]:
np.random.randint(10, size=(10, 10)).reshape(5, 20)

array([[1, 6, 2, 4, 9, 2, 1, 5, 4, 4, 9, 9, 1, 8, 3, 8, 4, 6, 2, 8],
       [2, 0, 8, 3, 5, 4, 7, 5, 9, 0, 2, 3, 4, 3, 7, 0, 7, 4, 4, 5],
       [8, 7, 0, 0, 8, 5, 7, 3, 2, 5, 3, 3, 2, 2, 8, 2, 5, 5, 8, 5],
       [2, 6, 6, 6, 7, 7, 9, 6, 2, 1, 2, 2, 9, 9, 0, 4, 5, 8, 8, 5],
       [6, 2, 8, 6, 5, 8, 7, 9, 7, 6, 7, 2, 4, 6, 1, 6, 2, 5, 5, 2]],
      dtype=int32)

In [160]:
np.random.randint(10, size=(10, 10)).reshape(5, 2, 10)

array([[[8, 9, 1, 3, 8, 2, 9, 5, 4, 1],
        [1, 4, 9, 5, 4, 9, 3, 1, 5, 3]],

       [[6, 0, 3, 3, 5, 2, 2, 0, 9, 8],
        [4, 5, 5, 1, 5, 6, 6, 5, 6, 6]],

       [[8, 8, 3, 3, 8, 1, 9, 4, 5, 5],
        [3, 6, 0, 3, 8, 3, 9, 8, 6, 3]],

       [[0, 5, 5, 7, 4, 7, 4, 9, 7, 5],
        [7, 3, 8, 8, 5, 3, 9, 3, 1, 9]],

       [[0, 1, 7, 3, 5, 0, 1, 6, 2, 2],
        [7, 1, 4, 1, 2, 2, 4, 6, 9, 5]]], dtype=int32)

#### linspace

Array von X bis Y mit Z Elementen erzeugen

Jedes Element hat den gleichen Abstand zueinander

In [163]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [166]:
np.arange(21) / 2

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

#### zeros, ones

In [175]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [176]:
np.ones(10, dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

#### hstack, vstack

Horizontal Stack, Vertical Stack

Arrays zusammenbauen

WICHTIG: Die Dimension müssen stimmen

In [178]:
f = c

In [179]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [189]:
# Aufgabe: Array mit 4, 7, 10 rechts anhängen
n = np.array([4, 7, 10]).reshape(-1, 1)

In [194]:
f = np.hstack([f, n])  # Diese Funktion benötigt als Parameter immer eine Liste

In [196]:
f

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [195]:
m = np.array([10, 11, 12, 13])

In [199]:
g = np.vstack([f, m])

In [200]:
g

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [201]:
# Aufgabe: Die Summen senkrecht unten anhängen

In [202]:
g.sum(axis=0)

array([22, 26, 30, 34])

In [204]:
h = np.vstack([g, g.sum(axis=0)])

In [205]:
h

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13],
       [22, 26, 30, 34]])

In [206]:
# Aufgabe: Die Summen waagrecht rechts anhängen

In [210]:
h.sum(axis=1)

array([ 10,  22,  34,  46, 112])

In [211]:
np.hstack([h, h.sum(axis=1).reshape(-1, 1)])

array([[  1,   2,   3,   4,  10],
       [  4,   5,   6,   7,  22],
       [  7,   8,   9,  10,  34],
       [ 10,  11,  12,  13,  46],
       [ 22,  26,  30,  34, 112]])